### PR TITLE
hotfix

### PR DESCRIPTION
**Pull request by kistenklaus**

### CODE REVIEW

**Comment by kistenklaus** [comment]
If you wanna run it this actually works =^)
https://github.com/mu-zero-HYPERLOOP/canzero/tree/gaslighting

**Comment by andtsa** [comment]
please never ever add node_modules to git 😂

**Comment by kistenklaus** [comment]
it was almost perfect =^). How you guys doing for the PoD? stressful times right?

**Comment by andtsa** [comment]
yeah... we're for leaving with the pod for Zurich in a week! how is it going for you?

**Comment by kistenklaus** [comment]
I'm going in 2 weeks my team will join a week afterwards. Delft is going early because your building for track right?

Going quite well, 6 club mate a day, integration hell is always fun.

**Comment by Zakrok09** [comment]
image
o_o

**Comment by FranciscoAmaro24** [comment]
lgtm

**Pull request closed without merging**
