### PR TITLE
FEAT: UI For creating route

### PR DESCRIPTION
**Pull request by Zakrok09**

### CODE REVIEW

**Comment by andtsa** [comment]
@Zakrok09 can you please gitignore package_lock.json?

**Comment by andtsa** [comment]
@Zakrok09 
image

**Comment by Zakrok09** [comment]
Did you `npm install` first?

**Comment by andtsa** [comment]
yes `npm i` solved it, I was confused by the 'not a file' error

**Comment by andtsa** [comment]
image
if you add too many blocks they fuse together

**Comment by andtsa** [comment]
image

**Comment by Zakrok09** [comment]
That's weird I specifically tested for this not to happen. I will try to see if a margin will fix it

**Comment by andtsa** [comment]
can you also add a margin at the bottom of this tab so that it doesn't overlap with the logs when they're extended? 
image

**Comment by andtsa** [comment]
also this no longer exists so pls remove :)
image

**Comment by andtsa** [comment]
image

**Comment by Zakrok09** [comment]
The thing with the logs panel is broken from the package. I made it be 30 height by default this should fix it. Also removed the RunInit bloat. The thing with the steps getting over each other is because of the size of the text. I will fix this as well rn

**Comment by andtsa** [comment]
I need these changes even if there are bugs, I will reopen the PR later if we find any

**Pull request merged**
